# Generated by Django 3.2.24 on 2024-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('pronouns', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=2000)),
            ],
        ),
    ]
