# Generated by Django 3.2.24 on 2024-02-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.CharField(default='Bio Coming!', max_length=2000),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(default='fake_email@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='firstname',
            field=models.CharField(default='First name', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lastname',
            field=models.CharField(default='Last name', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pronouns',
            field=models.CharField(default='Ask me about my pronouns!', max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(default='My job', max_length=30),
        ),
    ]
