# Generated by Django 3.2.24 on 2024-02-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pastoralprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('pronouns', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phonenumber', models.CharField(default='', max_length=12)),
                ('streetaddress', models.CharField(default='', max_length=500)),
                ('locality', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=15)),
                ('maritalstatus', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
