# Generated by Django 3.2.24 on 2024-02-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240208_1649'),
        ('home', '0005_firsttimer'),
    ]

    operations = [
    ]
