# Generated by Django 3.2.24 on 2024-02-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_0002_auto_20240208_1649_0005_firsttimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firsttimer',
            options={'verbose_name': 'First Timer', 'verbose_name_plural': 'First Timers'},
        ),
        migrations.AlterModelOptions(
            name='pastoralprofile',
            options={'verbose_name': 'Pastor Profile', 'verbose_name_plural': 'Pastor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pronouns',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
