# Generated by Django 3.2.24 on 2024-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240218_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('pronouns', models.CharField(default='', max_length=30)),
                ('profilepic', models.ImageField(default='static/images/profdefault.png', upload_to='')),
                ('role', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=100)),
                ('bio', models.CharField(default='', max_length=2000)),
            ],
            options={
                'verbose_name': 'Council Profile',
                'verbose_name_plural': 'Council Profiles',
            },
        ),
    ]
